export const LOGIN_INPUT = 'login/input'
export const REGISTER_INPUT = 'register/input'
export const BARANG_INPUT = 'barang/input'
export const SUPLIER_INPUT = 'suplier/input'
export const UPDATE_USER_INPUT = 'userUpdate/input'
export const UPDATE_PASSWORD_INPUT = 'upPass/input'
